### ISSUE TITLE
Setup Github Actions

### ISSUE THREAD

**Issue by AppManJones** [AppManJones/MobileShowcase#12]
### **Is your feature request related to a problem? Please describe.**

Currently, there is no automated way to ensure that both unit tests and snapshot tests are run when a pull request (PR) is opened or updated. This increases the risk of code being merged without fully passing tests, potentially introducing regressions or breaking changes. Manually running tests across multiple branches can lead to inconsistencies and errors.

**Describe the solution you'd like**

I propose setting up **GitHub Actions** to automatically run unit tests and snapshot tests for each PR. The tests must pass before a PR can be merged into the main branch. This will ensure that every commit is thoroughly tested and will provide the following benefits:
- Automatically verify that all tests (unit and snapshot) pass on each PR.
- Block merging until all checks have passed successfully.
- Catch any UI regressions (via snapshot tests) or logic bugs (via unit tests) early in the development process.

The integration will involve:
1. Creating a **GitHub Actions** workflow file (`.github/workflows/test.yml`) to run both snapshot and unit tests on each PR.
2. Configuring the workflow to run on all PR events (e.g., when a PR is opened or updated).
3. Enforcing branch protection rules so that the PR cannot be merged unless all checks pass.

**Describe alternatives you've considered**

- Relying on manual testing, which is prone to human error and inconsistencies.
- Running tests locally, but this doesn't provide centralized feedback for the entire team and lacks automation.

**Additional context**

Here’s an example of a possible **GitHub Actions** workflow configuration to run unit and snapshot tests:

```yaml
name: Test Suite

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1

    - name: Install dependencies
      run: xcodebuild -resolvePackageDependencies

    - name: Run unit tests
      run: xcodebuild test -scheme YourAppScheme -destination 'platform=iOS Simulator,name=iPhone 12'

    - name: Run snapshot tests
      run: xcodebuild test -scheme YourAppScheme -destination 'platform=iOS Simulator,name=iPhone 12'
```

**Branch Protection**: You will need to enable branch protection rules in GitHub to ensure that no PR can be merged into `main` unless all checks have passed. This can be configured under the repository’s settings:

1. Go to **Settings** -> **Branches** -> **Branch protection rules**.
2. Add a rule for the `main` branch.
3. Enable **Require status checks to pass before merging** and select the GitHub Actions tests to enforce this.

With this setup, GitHub Actions will automatically run all tests (unit and snapshot) whenever a PR is opened or updated. If any test fails, the PR will be blocked from merging until all issues are resolved.
