### ISSUE TITLE
Add post-merge integration tests

### ISSUE THREAD

**Issue by AppManJones** [AppManJones/MobileShowcase#13]
### **Is your feature request related to a problem? Please describe.**

We currently do not have integration tests that run after code is merged into the `main` branch. This creates the risk of post-merge regressions going unnoticed until later stages. Additionally, there is no system for attributing failed tests back to the original author, making it difficult to follow up on failures efficiently.

**Describe the solution you'd like**

I propose creating a suite of Xcode **UI tests** that run as integration tests after code has been merged into the `main` branch. These UI tests will help ensure that critical workflows remain intact after changes have been merged.

The UI tests should be:
1. Configured as a separate GitHub Action that runs **post-merge**.
2. Not part of the regular PR check process.
3. Include **attribution** for failed tests, allowing us to notify the appropriate author of the PR when a failure occurs.

The key tasks include:
- Setting up Xcode UI tests using XCTest.
- Creating a new GitHub Action workflow (`.github/workflows/ui_tests.yml`) that triggers after a successful merge to `main`.
- Adding notification functionality to alert the appropriate author (via email or Slack) when a test fails.

**Describe alternatives you've considered**

- Running the UI tests as part of the regular PR checks, but this could slow down the CI pipeline and is better suited for post-merge validation.
- Manually running UI tests, which would be time-consuming and inefficient.

**Additional context**

Here’s an example of a GitHub Action workflow for running UI tests post-merge:

```yaml
name: UI Test Integration Suite

on:
  push:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1

    - name: Install dependencies
      run: xcodebuild -resolvePackageDependencies

    - name: Run UI tests
      run: xcodebuild test -scheme YourAppScheme -destination 'platform=iOS Simulator,name=iPhone 12'

    - name: Notify author on failure
      if: failure()
      run: |
        echo "Notifying author of the failing tests."
        # Here you can add a script to send email or Slack notifications to the author of the commit.
```

**To attribute failed tests to the original PR author**:

- You can retrieve the commit metadata to find the author of the latest changes.
- Integrate with GitHub’s API or a notification service (such as Slack or email) to notify the author when the tests fail.

**Notification Attribution Example**:

1. **Retrieve the latest commit author**:
```bash
AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')
echo "Test failure attributed to: $AUTHOR"
```

2. **Notify the author using a service like Slack or email**:
   - Use GitHub’s API or a custom script to send notifications to the commit author.

By running these UI tests post-merge and notifying the original author upon failure, we can ensure that any issues introduced by merged code are promptly addressed, maintaining high-quality production builds.
